id: I556DFF33
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T20:51:22+00:00'
last_modified: '2022-06-07T20:30:07.744366+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2DB4613
  title: ལམ་རིམ་བླ་མ་བརྒྱུད་པའི་རྣམ་ཐར／
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    374D:
      image_group_id: I1PD27432
      title: ''
      total_pages: 622
      order: 1
      base_file: 374D.txt
    D7BF:
      image_group_id: I1PD27433
      title: ''
      total_pages: 664
      order: 2
      base_file: D7BF.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
